{% set name = "yapf" %}
{% set version = "0.33.0" %}
{% set sha256 = "c7bab16bab19c94a478e4f25fbcae545aa29c5f5fbe7c630f06ceafd807cc13b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - yapf = yapf:run_main
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - tomli >=2.0.1
    - python >=3.7

test:
  commands:
    - yapf --help
    - yapf --version
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/yapf
  license: Apache-2.0
  license_file: LICENSE
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
