{% set name = "yapf" %}
{% set version = "0.24.0" %}
{% set sha256 = "b249ee4a79f0bde2473ab2238dfbb311ae0e789b270779090f77df3269d74821" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - yapf = yapf:run_main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  commands:
    - yapf --help
    - yapf --version

about:
  home: https://github.com/google/yapf
  license: Apache 2.0
  summary: A formatter for Python files

extra:
  recipe-maintainers:
    - vamega
    - ericdill
